name: trygzerodegreedayscities_env
channels:
    - conda-forge
dependencies:
    - python=3.12.6 # Python version 3.6
    - cartopy       # Geographic plotting toolkit
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - scipy         # Common math/stats/science functions
    - xarray        # N-d labeled array library
    - os            # allows linux style commands with python
    - dask          # allows for parrallelization for IO